#!/usr/bin/env python3
"""Council App: local browser-based multi-agent chat."""

import os
import shutil
import sys
import tomllib
import logging
import getpass
from pathlib import Path

import uvicorn

APP_DIR = Path(__file__).resolve().parent
_user_cwd = Path(os.getcwd()).resolve()
os.chdir(APP_DIR)  # ensure backend imports resolve

from backend.state import SessionRegistry
from backend.app import create_app

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)

logger = logging.getLogger(__name__)


def _load_dotenv(env_path: Path) -> dict[str, str]:
    """Minimal .env parser — no third-party dependency."""
    env: dict[str, str] = {}
    if not env_path.is_file():
        return env
    for line in env_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip("\"'")
        if key:
            env[key] = value
    return env


def _apply_env_overrides(config: dict, env: dict[str, str]) -> None:
    """Apply COUNCIL_* environment variables as overrides to config dict."""
    overrides = {
        "COUNCIL_BINARY_CLAUDE": ("binaries", "claude", str),
        "COUNCIL_BINARY_CODEX": ("binaries", "codex", str),
        "COUNCIL_BINARY_OPENCODE": ("binaries", "opencode", str),
        "COUNCIL_MODEL_CLAUDE": ("models", "claude", str),
        "COUNCIL_MODEL_CODEX": ("models", "codex", str),
        "COUNCIL_MODEL_DEEPSEEK_PRO": ("models", "deepseek_pro", str),
        "COUNCIL_MODEL_DEEPSEEK_FLASH": ("models", "deepseek_flash", str),
        "COUNCIL_PROVIDER_CLAUDE": ("providers", "claude", str),
        "COUNCIL_PROVIDER_CODEX": ("providers", "codex", str),
        "COUNCIL_PROVIDER_DEEPSEEK": ("providers", "deepseek", str),
        "ANTHROPIC_API_KEY": ("api_keys", "claude", str),
        "OPENAI_API_KEY": ("api_keys", "codex", str),
        "OPENROUTER_API_KEY": ("api_keys", "openrouter", str),
        "DEEPSEEK_API_KEY": ("api_keys", "deepseek", str),
        "DEEPSEEK_FLASH_API_KEY": ("api_keys", "deepseek_flash", str),
        "COUNCIL_PORT": ("server", "port", int),
        "COUNCIL_HOST": ("server", "host", str),
    }
    for env_key, (section, key, cast) in overrides.items():
        value = env.get(env_key)
        if value is None:
            continue
        if cast is int:
            value = int(value)
        config.setdefault(section, {})[key] = value


def _check_cli_available(name: str) -> bool:
    """Check if a CLI tool is on PATH."""
    return shutil.which(name) is not None


def _prompt(default: str, label: str) -> str:
    suffix = f" [{default}]" if default else ""
    try:
        value = input(f"  {label}{suffix}: ").strip()
    except EOFError:
        return default
    return value or default


def _prompt_secret(label: str) -> str:
    try:
        return getpass.getpass(f"  {label} (hidden, Enter to skip): ").strip()
    except EOFError:
        return ""


def _append_env(lines: list[str], key: str, value: str) -> None:
    if value:
        lines.append(f"{key}={value}")


def _run_setup_wizard(config: dict) -> bool:
    """Interactive first-run setup wizard."""
    print("\n=== Council Setup ===\n")
    print("This writes a local .env file for Council. You can leave fields blank")
    print("and later use the web Config panel for per-session overrides.\n")

    agents = [
        ("Claude", "claude"),
        ("Codex", "codex"),
        ("Deepseek (via opencode)", "opencode"),
    ]

    for label, binary in agents:
        available = _check_cli_available(binary)
        status = "FOUND" if available else "NOT FOUND"
        print(f"  {label:30s} ({binary:10s})  [{status}]")

    print("\nProviders: claude_cli, codex_cli, opencode, openrouter, deepseek_api, custom")
    print("CLI providers still require their CLI to be installed and authenticated.\n")
    print("If a CLI is logged into a subscription or paid plan, Council uses that")
    print("same CLI access. API providers use tokens instead.\n")
    print("Council cannot perform interactive CLI login. Run each CLI's own")
    print("login/auth command in a terminal before using that CLI provider.\n")

    try:
        create_env = input("Create .env file now? [Y/n]: ").strip().lower()
    except EOFError:
        print("\nNo interactive stdin available. Re-run 'council --setup' in a terminal,")
        print("or copy .env.example to .env and edit it manually.\n")
        return False
    if create_env in ("n", "no"):
        print("Skipping .env creation. Run 'council --setup' anytime to re-run.\n")
        return False

    env_path = APP_DIR / ".env"
    lines = [
        "# Council environment - generated by setup wizard",
        "",
    ]

    lines.append("# ---- Providers ----")
    _append_env(lines, "COUNCIL_PROVIDER_CLAUDE", _prompt("claude_cli", "Claude provider"))
    _append_env(lines, "COUNCIL_PROVIDER_CODEX", _prompt("codex_cli", "Codex provider"))
    _append_env(lines, "COUNCIL_PROVIDER_DEEPSEEK", _prompt("opencode", "Deepseek provider"))
    lines.append("")

    lines.append("# ---- Model IDs ----")
    _append_env(lines, "COUNCIL_MODEL_CLAUDE", _prompt(
        config.get("models", {}).get("claude", "claude-opus-4-7"),
        "Claude model",
    ))
    _append_env(lines, "COUNCIL_MODEL_CODEX", _prompt(
        config.get("models", {}).get("codex", "gpt-5.5"),
        "Codex model",
    ))
    _append_env(lines, "COUNCIL_MODEL_DEEPSEEK_PRO", _prompt(
        config.get("models", {}).get("deepseek_pro", "deepseek/deepseek-v4-pro"),
        "Deepseek Pro model",
    ))
    _append_env(lines, "COUNCIL_MODEL_DEEPSEEK_FLASH", _prompt(
        config.get("models", {}).get("deepseek_flash", "deepseek/deepseek-v4-flash"),
        "Deepseek Flash summarizer model",
    ))
    lines.append("")

    lines.append("# ---- API keys ----")
    print("\nAPI keys are optional. They will be written to .env if provided.")
    _append_env(lines, "ANTHROPIC_API_KEY", _prompt_secret("Anthropic/Claude API key"))
    _append_env(lines, "OPENAI_API_KEY", _prompt_secret("OpenAI/Codex API key"))
    _append_env(lines, "OPENROUTER_API_KEY", _prompt_secret("OpenRouter API key"))
    _append_env(lines, "DEEPSEEK_API_KEY", _prompt_secret("Deepseek API key"))
    _append_env(lines, "DEEPSEEK_FLASH_API_KEY", _prompt_secret("Deepseek Flash API key"))
    lines.append("")

    lines.append("# ---- Binary paths ----")
    for label, binary in agents:
        available = _check_cli_available(binary)
        current_path = shutil.which(binary) or ""
        prompt = (
            f"Path to {label} binary"
            if not available else
            f"Path to {label} binary (found {current_path})"
        )
        try:
            custom = input(f"  {prompt} (Enter to keep/skip): ").strip()
        except EOFError:
            custom = ""
        if custom:
            if binary == "opencode":
                lines.append(f"COUNCIL_BINARY_OPENCODE={custom}")
            else:
                lines.append(f"COUNCIL_BINARY_{binary.upper()}={custom}")
    lines.append("")
    env_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nCreated {env_path}")
    print("Edit it anytime to adjust settings.\n")

    env = _load_dotenv(env_path)
    _apply_env_overrides(config, env)
    return True


def _default_project_root() -> Path:
    if len(sys.argv) > 1:
        return Path(sys.argv[1]).expanduser().resolve()
    return _user_cwd


def main():
    project_root = _default_project_root()

    config_path = APP_DIR / "config.toml"
    with open(config_path, "rb") as f:
        config = tomllib.load(f)

    env_path = APP_DIR / ".env"

    if "--setup" in sys.argv:
        created = _run_setup_wizard(config)
        if created:
            print("Setup complete. Restart council without --setup to start chatting.\n")
        else:
            print("Setup exited without writing .env.\n")
        return

    env = _load_dotenv(env_path)
    _apply_env_overrides(config, env)

    if not env_path.is_file():
        print("\n  No .env file found.")
        print("  Run 'council --setup' for guided provider/model/token setup,")
        print("  or use the web Config panel after Council starts.")
        print(f"  Template: {env_path.parent / '.env.example'}\n")

        missing = [
            label for label, binary in
            [("Claude (claude)", "claude"),
             ("Codex (codex)", "codex"),
             ("Deepseek (opencode)", "opencode")]
            if not _check_cli_available(binary)
        ]
        if missing:
            print(f"  Missing CLIs: {', '.join(missing)}")
            print("  Install the CLIs and authenticate them before using those agents.\n")
        else:
            print("  CLI tools were found on PATH, but Council cannot verify login state.")
            print("  If dispatch asks for auth, complete the CLI's own login flow first.\n")

    registry = SessionRegistry(
        council_root=APP_DIR,
        config=config,
        config_path=config_path,
        default_project_root=project_root,
    )
    registry.load_all()

    port = config["server"]["port"]
    host = config["server"]["host"]

    app = create_app(registry)

    print(f"\nCouncil running at http://{host}:{port}")
    print(f"Sessions: {registry.sessions_dir}")
    print(f"Active session: {registry.active_session_id}")
    print(f"Default project for new registries: {project_root}")
    print("Open the URL in your browser. Press Ctrl+C to stop.\n")

    uvicorn.run(app, host=host, port=port, log_level="warning")


if __name__ == "__main__":
    main()
