#!/usr/bin/env python3
"""Council App: local browser-based multi-agent chat."""

import os
import shutil
import sys
import tomllib
import logging
from pathlib import Path

import uvicorn

APP_DIR = Path(__file__).resolve().parent
_user_cwd = Path(os.getcwd()).resolve()
os.chdir(APP_DIR)  # ensure backend imports resolve

from backend.state import SessionRegistry
from backend.app import create_app

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)

logger = logging.getLogger(__name__)


def _load_dotenv(env_path: Path) -> dict[str, str]:
    """Minimal .env parser — no third-party dependency."""
    env: dict[str, str] = {}
    if not env_path.is_file():
        return env
    for line in env_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip("\"'")
        if key:
            env[key] = value
    return env


def _apply_env_overrides(config: dict, env: dict[str, str]) -> None:
    """Apply COUNCIL_* environment variables as overrides to config dict."""
    overrides = {
        "COUNCIL_BINARY_CLAUDE": ("binaries", "claude", str),
        "COUNCIL_BINARY_CODEX": ("binaries", "codex", str),
        "COUNCIL_BINARY_OPENCODE": ("binaries", "opencode", str),
        "COUNCIL_MODEL_CLAUDE": ("models", "claude", str),
        "COUNCIL_MODEL_CODEX": ("models", "codex", str),
        "COUNCIL_MODEL_DEEPSEEK_PRO": ("models", "deepseek_pro", str),
        "COUNCIL_MODEL_DEEPSEEK_FLASH": ("models", "deepseek_flash", str),
        "COUNCIL_PORT": ("server", "port", int),
        "COUNCIL_HOST": ("server", "host", str),
    }
    for env_key, (section, key, cast) in overrides.items():
        value = env.get(env_key)
        if value is None:
            continue
        if cast is int:
            value = int(value)
        config.setdefault(section, {})[key] = value


def _check_cli_available(name: str) -> bool:
    """Check if a CLI tool is on PATH."""
    return shutil.which(name) is not None


def _run_setup_wizard(config: dict) -> None:
    """Interactive first-run setup wizard."""
    print("\n=== Council Setup ===\n")
    print("Council delegates auth to individual CLIs. Each agent needs its")
    print("own CLI installed and authenticated.\n")

    agents = [
        ("Claude", "claude"),
        ("Codex", "codex"),
        ("Deepseek (via opencode)", "opencode"),
    ]

    for label, binary in agents:
        available = _check_cli_available(binary)
        status = "FOUND" if available else "NOT FOUND"
        print(f"  {label:30s} ({binary:10s})  [{status}]")

    print("\nSee .env.example for all configurable options.\n")

    create_env = input("Create .env file now? [Y/n]: ").strip().lower()
    if create_env in ("n", "no"):
        print("Skipping .env creation. Run 'council --setup' anytime to re-run.\n")
        return

    env_path = APP_DIR / ".env"
    lines = [
        "# Council environment — generated by setup wizard",
        "",
    ]
    for label, binary in agents:
        available = _check_cli_available(binary)
        if not available:
            custom = input(f"  Path to {label} binary (or Enter to skip): ").strip()
            if custom:
                if binary == "opencode":
                    lines.append(f"COUNCIL_BINARY_OPENCODE={custom}")
                else:
                    lines.append(f"COUNCIL_BINARY_{binary.upper()}={custom}")
    lines.append("")
    env_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nCreated {env_path}")
    print("Edit it anytime to adjust settings.\n")

    env = _load_dotenv(env_path)
    _apply_env_overrides(config, env)


def _default_project_root() -> Path:
    if len(sys.argv) > 1:
        return Path(sys.argv[1]).expanduser().resolve()
    return _user_cwd


def main():
    project_root = _default_project_root()

    config_path = APP_DIR / "config.toml"
    with open(config_path, "rb") as f:
        config = tomllib.load(f)

    env_path = APP_DIR / ".env"

    if "--setup" in sys.argv:
        _run_setup_wizard(config)
        print("Setup complete. Restart council without --setup to start chatting.\n")
        return

    env = _load_dotenv(env_path)
    _apply_env_overrides(config, env)

    if not env_path.is_file():
        print("\n  No .env file found. Run 'council --setup' for guided setup.")
        print(f"  Copy .env.example → .env to customize.({env_path.parent / '.env.example'})\n")

        missing = [
            label for label, binary in
            [("Claude (claude)", "claude"),
             ("Codex (codex)", "codex"),
             ("Deepseek (opencode)", "opencode")]
            if not _check_cli_available(binary)
        ]
        if missing:
            print(f"  Missing CLIs: {', '.join(missing)}")
            print("  Install the CLIs and authenticate them before using those agents.\n")

    registry = SessionRegistry(
        council_root=APP_DIR,
        config=config,
        config_path=config_path,
        default_project_root=project_root,
    )
    registry.load_all()

    port = config["server"]["port"]
    host = config["server"]["host"]

    app = create_app(registry)

    print(f"\nCouncil running at http://{host}:{port}")
    print(f"Sessions: {registry.sessions_dir}")
    print(f"Active session: {registry.active_session_id}")
    print(f"Default project for new registries: {project_root}")
    print("Open the URL in your browser. Press Ctrl+C to stop.\n")

    uvicorn.run(app, host=host, port=port, log_level="warning")


if __name__ == "__main__":
    main()
